namespace GenshinToolbox.ArtScraper;

enum ArtSet
{
	Adventurer,
	ArchaicPetra,
	Berserker,
	BlizzardStrayer,
	BloodstainedChivalry,
	BraveHeart,
	CrimsonWitchOfFlames,
	DefendersWill,
	EmblemOfSeveredFate,
	Gambler,
	GladiatorsFinale,
	HeartOfDepth,
	Initiate,
	Instructor,
	Lavawalker,
	LuckyDog,
	MaidenBeloved,
	MartialArtist,
	NoblesseOblige,
	PaleFlame,
	PrayersForDestiny,
	PrayersForIllumination,
	PrayersForWisdom,
	PrayersToSpringtime,
	ResolutionOfSojourner,
	RetracingBolide,
	Scholar,
	ShimenawasReminiscence,
	TenacityOfTheMillelith,
	TheExile,
	ThunderingFury,
	Thundersoother,
	TinyMiracle,
	TravelingDoctor,
	ViridescentVenerer,
	WanderersTroupe,
}

partial class Scraper
{
	private static readonly Dictionary<ArtSet, string> SetNames = new()
	{
		{ ArtSet.GladiatorsFinale, "Gladiator's Finale" },
		{ ArtSet.WanderersTroupe, "Wanderer's Troupe" },
		{ ArtSet.ViridescentVenerer, "Viridescent Venerer" },
		{ ArtSet.ThunderingFury, "Thundering Fury" },
		{ ArtSet.Thundersoother, "Thundersoother" },
		{ ArtSet.CrimsonWitchOfFlames, "Crimson Witch of Flames" },
		{ ArtSet.Lavawalker, "Lavawalker" },
		{ ArtSet.ArchaicPetra, "Archaic Petra" },
		{ ArtSet.RetracingBolide, "Retracing Bolide" },
		{ ArtSet.MaidenBeloved, "Maiden Beloved" },
		{ ArtSet.NoblesseOblige, "Noblesse Oblige" },
		{ ArtSet.BloodstainedChivalry, "Bloodstained Chivalry" },
		{ ArtSet.BlizzardStrayer, "Blizzard Strayer" },
		{ ArtSet.HeartOfDepth, "Heart of Depth" },
		{ ArtSet.TenacityOfTheMillelith, "Tenacity of the Millelith" },
		{ ArtSet.PaleFlame, "Pale Flame" },
		{ ArtSet.EmblemOfSeveredFate, "Emblem of Severed Fate" },
		{ ArtSet.ShimenawasReminiscence, "Shimenawa's Reminiscence" },
		{ ArtSet.Instructor, "Instructor" },
		{ ArtSet.TheExile, "The Exile" },
		{ ArtSet.ResolutionOfSojourner, "Resolution of Sojourner" },
		{ ArtSet.MartialArtist, "Martial Artist" },
		{ ArtSet.DefendersWill, "Defender's Will" },
		{ ArtSet.TinyMiracle, "Tiny Miracle" },
		{ ArtSet.BraveHeart, "Brave Heart" },
		{ ArtSet.Gambler, "Gambler" },
		{ ArtSet.Scholar, "Scholar" },
		{ ArtSet.PrayersForWisdom, "Prayers for Wisdom" },
		{ ArtSet.PrayersToSpringtime, "Prayers to Springtime" },
		{ ArtSet.PrayersForIllumination, "Prayers for Illumination" },
		{ ArtSet.PrayersForDestiny, "Prayers for Destiny" },
		{ ArtSet.Berserker, "Berserker" },
		{ ArtSet.LuckyDog, "Lucky Dog" },
		{ ArtSet.TravelingDoctor, "Traveling Doctor" },
		{ ArtSet.Adventurer, "Adventurer" },
		{ ArtSet.Initiate, "Initiate" },
	};
}